### PR TITLE
Calculator Component

### PR DESCRIPTION
**Pull request by felixodette**
* Delete all the boilerplate from CRA (text, images, styles).
* Create a directory called components.
* Inside components, create a new Calculator.js file.
* In Calculator.js, create a React component that matches provided design.

### CODE REVIEW

**Review by elyor-doniyorov — CHANGES_REQUESTED** [review]
Hi @felixodette, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ There are no linter errors
✔️ Descriptive PR title and description
✔️ etc.

## Required Changes ♻️
- [ ] You still need to delete boilerplate code from `public` folder(texts, images, styles).
- [ ] There is an error in the console, kindly fix it 👇 
Screenshot (268)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by felixodette** [comment]
Good looking out. I've removed the unnecessary file.

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @felixodette 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Great work removing all boilerplate files from the `src` directory. 💯 


 ## Required Changes ♻️
### I am making the required suggestion in the summary because the following files are not in the **_files changed_** section of the pull request page.

- The previous reviewer requested that you remove all boilerplates in the _**public**_ directory. In light of this, kindly remove the following files from the public directory:
  -  favicon.ico
  - logo192.png
  - logo512.png
  - manifest.json
  - robots.txt

## Optional suggestions

- It would be nice to include commands for installing this project in your `README.md` file just before the command for starting the project. I would recommend that instruct those willing to clone your repository to run `npm install`. This will install all the dependencies used to bootstrap this project. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by felixodette** [comment]
Hi @Gambit142, I've removed the files in the public directory

**Review by danmainah — APPROVED** [review]
Hi @felixodette, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Github flow was correctly used


 # Required Changes ♻️

- [ ]  I noticed you deleted the whole public folder kindly restore it and add the index.html file because your project won't run without it.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by felixodette** [comment]
All sorted. Thanks guys!

**Comment by Gambit142** [comment]
Hi @felixodette, great work implementing the changes suggested. Keep up the good work 👍

**Pull request merged**
